### PR TITLE
Add proper warrenty and legal information

### PR DESCRIPTION
**Pull request by Armada3334**
This ensures Nurah is not legally liable for whatever a user wants to do with the software.

### CODE REVIEW

**Review by nurahwolf — CHANGES_REQUESTED** [review]
You are going to want to change the whole of the license, not just the bottom of it

**Comment by nurahwolf** [comment]
@Armada3334 Thanks! Though you probably want to change the full license, not just amend it.
Consider changing the license to https://unlicense.org ?

**Comment by Armada3334** [comment]
I've updated the license to the requested changes.

**Review by Armada3334 — COMMENTED** [review]
Completed changes

**Comment by nurahwolf** [comment]
Awesome, all good thanks :)

**Pull request merged**
